extends:
  brightspace/wct-polymer-3-config
rules:
  eqeqeq: [2, "always", {"null": "ignore"}]
  no-useless-escape: 0
  object-shorthand: [2, "never"]
globals:
  fastdom: false
env:
  node: true
  es6: true
